-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT into friend (name) VALUES ('Shruthi');
-- INSERT into friend (name) VALUES ('Abhishek');
-- INSERT into friend (name) VALUES ('Avinash');
